### ISSUE TITLE
Permission Denied stacktrace

### ISSUE THREAD

**Issue by enriquejosepadilla** [GoogleCloudPlatform/django-cloud-deploy#132]
I think from expired credentials.:

[1/11] In order to deploy your application, you must allow Django Deploy to access your Google account.
You have logged in with account [epad@google.com]. Do you want to use it? [y/N]: y
[2/11] Enter a Google Cloud Platform Project ID, or leave blank to use
[django-255691]: 
[3/11] Enter a Google Cloud Platform project name, or leave blank to use
[Django Project]: 
[4/11] In order to deploy your application, you must enable billing for your Google Cloud Project.
You have the following existing billing accounts: 
1. Python-Billing
Please enter your numeric choice or press [Enter] to create a new billing account: 1
[5/11] Enter a password for the default database user "postgres"
Password: 
Password (again): 
[6/11] Enter a new directory path to store project source, or leave blank to use
[/usr/local/google/home/epad/django-project]: 
The directory '/usr/local/google/home/epad/django-project' already exists, replace it's contents [y/N]: y
[7/11] Enter a Django project name, or leave blank to use
[mysite]:      
[8/11] Enter a Django app name, or leave blank to use
[home]: 
[9/11] Enter a name for the Django superuser, or leave blank to use
[admin]: 
[10/11] Enter a password for the Django superuser "admin"
Password: 
Password (again): 
[11/11] Enter a e-mail address for the Django superuser, or leave blank to use
[test@example.com]: 
Traceback (most recent call last):
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/bin/django-cloud-deploy", line 11, in <module>
    load_entry_point('django-cloud-deploy', 'console_scripts', 'django-cloud-deploy')()
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/django_cloud_deploy.py", line 57, in main
    args.func(args)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/django_cloud_deploy.py", line 30, in _new
    new.main(args)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/cli/new.py", line 199, in main
    actual_parameters['credentials'])
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/workflow/__init__.py", line 55, in __init__
    self._deploygke_workflow = _deploygke.DeploygkeWorkflow(credentials)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/workflow/_deploygke.py", line 39, in __init__
    credentials)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/cloudlib/container.py", line 94, in from_credentials
    credentials)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/cloudlib/container.py", line 74, in __init__
    self._create_docker_client(credentials)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/cloudlib/container.py", line 88, in _create_docker_client
    registry='https://gcr.io')
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/docker/client.py", line 183, in login
    return self.api.login(*args, **kwargs)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/docker/api/daemon.py", line 147, in login
    response = self._post_json(self._url('/auth'), data=req_data)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/docker/api/client.py", line 257, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/docker/api/client.py", line 194, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

**Comment by wangxf123456** [comment]
I am not sure how this happened. I created a credentials object several days ago and kept reusing it. This does not happen to me. Maybe we should debug this together.

**Comment by wangxf123456** [comment]
I debugged this with @enriquejosepadilla. This is because docker is not correctly setup. It should be fixed by #117. After the pull request is merged, the tool will complain about docker not able to run, instead of showing the stacktrace.
