### ISSUE TITLE
UnboundLocalError:local variable 'p' referenced before assignment during "django-cloud-deploy new"

### ISSUE THREAD

**Issue by brianquinlan** [GoogleCloudPlatform/django-cloud-deploy#145]
## Issue running command
django-cloud-deploy new

## Environment information

Django Cloud Deploy: [0.1.0]

Platform: [Darwin-17.7.0-x86_64-i386-64bit]

Gcloud Version: [215.0.0]

Cloud SQL Proxy Version: [Cloud SQL Proxy: version 1.13; sha ac834ce67862b7c4ed8bdbe86e664572f820c245 built Tue Oct  9 23:39:16 UTC 2018]

Python Version: [3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]]

Docker Version: [Docker version 18.09.0, build 4d60db4]

## Traceback
```.pytb
Traceback (most recent call last):
  File "/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/django_cloud_deploy.py", line 36, in _new
    new.main(args)
  File "/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/cli/new.py", line 117, in main
    tool_requirements.check_and_handle_requirements(console, args.backend)
  File "/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/tool_requirements.py", line 294, in check_and_handle_requirements
    req.check_and_handle(console)
  File "/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/tool_requirements.py", line 124, in check_and_handle
    cls.check()
  File "/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/tool_requirements.py", line 210, in check
    p.close()
UnboundLocalError: local variable 'p' referenced before assignment

```

**Comment by wangxf123456** [comment]
We just fixed this in#142. We will do a release later today.
