### ISSUE TITLE
FileNotFoundError:[Errno 2] No such file or directory: '/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/skeleton/templates/.gcloudignore' during "django-cloud-deploy new"

### ISSUE THREAD

**Issue by brianquinlan** [GoogleCloudPlatform/django-cloud-deploy#146]
## Issue running command
django-cloud-deploy new

## Environment information

Django Cloud Deploy: [0.1.1]

Platform: [Darwin-17.7.0-x86_64-i386-64bit]

Gcloud Version: [215.0.0]

Cloud SQL Proxy Version: [Cloud SQL Proxy: version 1.13; sha ac834ce67862b7c4ed8bdbe86e664572f820c245 built Tue Oct  9 23:39:16 UTC 2018]

Python Version: [3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]]

Docker Version: [Docker version 18.09.0, build 4d60db4]

## Traceback
```.pytb
Traceback (most recent call last):
  File "/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/django_cloud_deploy.py", line 36, in _new
    new.main(args)
  File "/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/cli/new.py", line 213, in main
    backend=args.backend)
  File "/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/workflow/__init__.py", line 194, in create_and_deploy_new_project
    image_tag=image_name)
  File "/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/skeleton/source_generator.py", line 774, in generate_all_source_files
    self.app_engine_file_generator.generate(project_name, project_dir)
  File "/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/skeleton/source_generator.py", line 493, in generate
    self._generate_ignore(project_dir)
  File "/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/skeleton/source_generator.py", line 501, in _generate_ignore
    self._render_file(template_path, output_path)
  File "/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/skeleton/source_generator.py", line 94, in _render_file
    with open(template_path) as template_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bquinlan/django_deploy/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/skeleton/templates/.gcloudignore'

```

**Comment by enriquejosepadilla** [comment]
This is due to the upload process to pypi is missing the .gcloudignore file.
