### ISSUE TITLE
ProjectExistsError:the project "django-234704" already exists during "django-cloud-deploy new"

### ISSUE THREAD

**Issue by enriquejosepadilla** [GoogleCloudPlatform/django-cloud-deploy#162]
## Issue running command
django-cloud-deploy new

## Please describe what is wrong

Project id should validate if it can be used when the user is being prompted, not after all of the prompts in step 1.

## Environment information

Django Cloud Deploy: [0.1.4]

Platform: [Linux-4.18.10-1rodete2-amd64-x86_64-with-Debian-rodete-rodete]

Gcloud Version: [225.0.0]

Cloud SQL Proxy Version: [Cloud SQL Proxy: version 1.13; sha ac834ce67862b7c4ed8bdbe86e664572f820c245 built Tue Oct  9 23:39:16 UTC 2018]

Python Version: [3.5.4rc1 (default, Jul 25 2017, 08:53:34)  [GCC 7.3.0]]

Docker Version: [Docker version 18.06.1-ce, build e68fc7a]

## Traceback
```.pytb
Traceback (most recent call last):
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/cloudlib/project.py", line 99, in create_project
    response = request.execute()
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/venv/lib/python3.5/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/venv/lib/python3.5/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 409 when requesting https://cloudresourcemanager.googleapis.com/v1/projects?alt=json returned "Requested entity already exists">

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/django_cloud_deploy.py", line 36, in _new
    new.main(args)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/cli/new.py", line 213, in main
    backend=args.backend)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/workflow/__init__.py", line 162, in create_and_deploy_new_project
    project_creation_mode)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/workflow/_project.py", line 79, in create_project
    project_id, project_name)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/cloudlib/project.py", line 116, in create_and_set_project
    self.create_project(project_id, project_name)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/cloudlib/project.py", line 103, in create_project
    'the project "{}" already exists'.format(project_id)) from e
django_cloud_deploy.cloudlib.project.ProjectExistsError: the project "django-234704" already exists

```

**Comment by enriquejosepadilla** [comment]
Currently this is not easy to resolve due to the fact that there is no way to check if a project-id currently exists. Reference https://github.com/googleapis/google-api-go-client/issues/173

Possible solution is to prepend django-xxxx-{{project-id}}
