### ISSUE TITLE
RefreshError:('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}') during "django-cloud-deploy new"

### ISSUE THREAD

**Issue by brianquinlan** [GoogleCloudPlatform/django-cloud-deploy#190]
## Issue running command
django-cloud-deploy new

## Please describe what is wrong

It looks like this error is caused by a very old gant, I see the same error when running gcloud:

$ gcloud projects list
ERROR: (gcloud.projects.list) There was a problem refreshing your current auth tokens: invalid_grant: Bad Request
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.

## Environment information

Django Cloud Deploy: [0.1.4]

Platform: [Windows-10.0.17134]

Gcloud Version: [231.0.0]

Cloud SQL Proxy Version: [Cloud SQL Proxy: version 1.13; sha ac834ce67862b7c4ed8bdbe86e664572f820c245 built Tue Oct  9 23:39:16 UTC 2018]

Python Version: [3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)]]

Docker Version: [Not installed or not on PATH]

## Traceback
```.pytb
Traceback (most recent call last):
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\django_cloud_deploy\django_cloud_deploy.py", line 36, in _new
    new.main(args)
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\django_cloud_deploy\cli\new.py", line 191, in main
    actual_parameters.get('credentials', None))
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\django_cloud_deploy\cli\prompt.py", line 789, in prompt
    only_open_accounts=True)
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\django_cloud_deploy\cloudlib\billing.py", line 102, in list_billing_accounts
    response = request.execute()
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\google_auth_httplib2.py", line 187, in request
    self._request, method, uri, request_headers)
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\google\auth\credentials.py", line 122, in before_request
    self.refresh(request)
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\google\oauth2\credentials.py", line 136, in refresh
    self._client_secret))
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\google\oauth2\_client.py", line 237, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\google\oauth2\_client.py", line 111, in _token_endpoint_request
    _handle_error_response(response_body)
  File "c:\users\brian\documents\github\django-deploy\lib\site-packages\google\oauth2\_client.py", line 61, in _handle_error_response
    error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')

```

**Comment by enriquejosepadilla** [comment]
Would this mean you had old credentials stored ?

**Comment by deepaknaikhnvrm** [comment]
I am facing the same issue with old stored credentials
