### ISSUE TITLE
Error running django-cloud-deploy-new --use-existing-project

### ISSUE THREAD

**Issue by josiahdahl** [GoogleCloudPlatform/django-cloud-deploy#204]
## Issue running command
django-cloud-deploy new

## Environment information

Django Cloud Deploy: [0.1.5]

Platform: [Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic]

Gcloud Version: [233.0.0]

Cloud SQL Proxy Version: [Cloud SQL Proxy: version 1.13; sha ac834ce67862b7c4ed8bdbe86e664572f820c245 built Tue Oct  9 23:39:16 UTC 2018]

Python Version: [3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]]

Docker Version: [Docker version 18.09.0, build 4d60db4]

## Traceback
```.pytb
Traceback (most recent call last):
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/django_cloud_deploy.py", line 36, in _new
    new.main(args)
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/cli/new.py", line 213, in main
    backend=args.backend)
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/workflow/__init__.py", line 214, in create_and_deploy_new_project
    project_id, required_services)
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/workflow/_enable_service.py", line 53, in enable_required_services
    project_id, service['name'])
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/cloudlib/enable_service.py", line 51, in enable_service_sync
    response = request.execute()
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://serviceusage.googleapis.com/v1/projects/django-on-gae3/services/compute.googleapis.com:enable?alt=json returned "Operation does not satisfy the following requirements: tos/cloud {The terms of service for this service must be accepted. Please visit the Developers Console to accept the service's terms of service., https://console.developers.google.com/terms/cloud}">

```

**Comment by brianquinlan** [comment]
What we probably need to do is catch this specific exception and give it special treatment, prompting the user to accept the ToS (but it is probably OK to abort the flow). Maybe convert this into a UserError and allow it to propagate to the top level?

Another approach would be to treat this as a requirement - we make a harmless API call at startup...but we don't have credentials at that point.

**Comment by enriquejosepadilla** [comment]
Yeah, theres no try catch around that API Call. Ideally for the best user experience we can accept the TOS as an API call, but in the meantime either we accept it for them beforehand, or we make it a requirement that the account used must have accepted the TOS.

**Comment by brianquinlan** [comment]
I don't think that we can accept the TOS in an API call because this is something that the user must agree to themselves.

**Comment by enriquejosepadilla** [comment]
It can be a TOS prompt jaja
