### ISSUE TITLE
django-cloud-deploy new --use-existing-project crashes when the user doesn't have permission to deploy

### ISSUE THREAD

**Issue by josiahdahl** [GoogleCloudPlatform/django-cloud-deploy#205]
## Issue running command
django-cloud-deploy new

## Please describe what is wrong
`django-cloud-deploy new --use-existing-project` crashes when the user doesn't have permission to deploy

## Environment information

Django Cloud Deploy: [0.1.5]

Platform: [Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic]

Gcloud Version: [233.0.0]

Cloud SQL Proxy Version: [Cloud SQL Proxy: version 1.13; sha ac834ce67862b7c4ed8bdbe86e664572f820c245 built Tue Oct  9 23:39:16 UTC 2018]

Python Version: [3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]]

Docker Version: [Docker version 18.09.0, build 4d60db4]

## Traceback
```.pytb
Traceback (most recent call last):
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/pexpect/spawnbase.py", line 166, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/pexpect/spawnbase.py", line 171, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/workflow/_deploygae.py", line 63, in deploy_gae_app
    process.expect('Do you want to continue (Y/n)?')
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/pexpect/expect.py", line 117, in expect_loop
    return self.eof(e)
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/pexpect/expect.py", line 63, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7fa986890f28>
command: /home/jdahl/.local/google-cloud-sdk/bin/gcloud
args: ['/home/jdahl/.local/google-cloud-sdk/bin/gcloud', 'app', 'deploy', '/home/jdahl/Code/scratch/django-on-gae3/app.yaml', '--project=django-on-gae3']
buffer (last 100 chars): b''
before (last 100 chars): b' 8\r\n\r\n\x1b[1;31mERROR:\x1b[0m (gcloud.app.deploy) PERMISSION_DENIED: The caller does not have permission\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 31001
child_fd: 18
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'Do you want to continue (Y/n)?')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/django_cloud_deploy.py", line 36, in _new
    new.main(args)
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/cli/new.py", line 213, in main
    backend=args.backend)
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/workflow/__init__.py", line 240, in create_and_deploy_new_project
    project_id, django_directory_path)
  File "/home/jdahl/Code/scratch/django-deploy/lib/python3.6/site-packages/django_cloud_deploy/workflow/_deploygae.py", line 69, in deploy_gae_app
    'of process: \n{}').format(process.before))
django_cloud_deploy.workflow._deploygae.DeployNewAppError: Error occured when trying to deploy GAE application. Output of process: 
b'      (supports standard and flexible)\r\n [10] cancel\r\nPlease enter your numeric choice:  8\r\n\r\n\x1b[1;31mERROR:\x1b[0m (gcloud.app.deploy) PERMISSION_DENIED: The caller does not have permission\r\n'

```

**Comment by brianquinlan** [comment]
Here is the relevant code:
https://github.com/GoogleCloudPlatform/django-cloud-deploy/blob/b82eddd122917c5614d66e3ffc20e65e8a12dca2/django_cloud_deploy/workflow/_deploygae.py#L28

Are you sure that you can't deploy app engine apps using some sort of quiet mode? If so then you could just check the return code and print the contents of stderr if it is not zero.

**Comment by enriquejosepadilla** [comment]
We specifically tried quiet mode and it did not work. That was ~ a month ago so maybe they have added it in now, will try it again though. I believe the user cut off the error though because rerunning it i got the following: 

```bash
 94 b'      (supports standard and flexible)\r\n [10] cancel\r\nPlease enter your numeric choice:  8\r\n\r\n\x1b[1;31mERROR:\x1b[0m (gcloud.app.deploy) PERMISSION_DENIED: The caller does not have permission\r\n- \'@type\': type.googleapis.com/google.rpc.DebugInfo\r\n  detail: "[ORI    GINAL ERROR] generic::permission_denied: com.google.apps.framework.auth.IamPermissionDeniedException:\\\r\n    \\ IAM authority does not have the permission \'appengine.applications.create\' required\\\r\n    \\ for action Applications_CreateApplication on resource \'apps/djang    o-on-gae6\'.\\\r\n    \\ Explanation:  Security Context: ValidatedSecurityContextWithSystemAuthorizationPolicy{delegate=ValidatedSecurityContextWithObligations{delegate=ValidatedSecurityContextWithPeer{delegate=ContextWithGaiaSession{delegate=ValidatedIamSecurityContext{user=ga    iauser/0xfbe7764f4d,\\\r\n    \\ creds=EndUserCreds{loggable_credential { type: GAIA_MINT loggable_gaia_mint\\\r\n    \\ { } }}, peer=protocol=loas;psp_version=0;level=strong_privacy_and_integrity;host=ojdg63.prod.google.com;is_authenticated_host=false;role=apphosting;security_    realms=campus-pry;is_delegated=false;user_type=MDB_USER_NON_PERSON,\\\r\n    \\ InternalIAMIdentity{log=loggable_peer { username: \\"apphosting\\" primary_role:\\\r\n    \\ \\"apphosting\\" unauthenticated_host: \\"ojdg63.prod.google.com\\" jobname_chosen_by_user:\\\r\n    \\ \    \"prod-appengine.admin.server\\" unauthenticated_borg_cell: \\"oj\\" }}}}}}}"\r\n'
```

**Comment by josiahdahl** [comment]
@enriquejosepadilla what I posted was the full dump of the crash report file
