### ISSUE TITLE
Remove redundant warnings from test

### ISSUE THREAD

**Issue by wangxf123456** [GoogleCloudPlatform/django-cloud-deploy#220]
The following warning messages are redundant.

```pytb
WARNING: Logging before flag parsing goes to stderr.
W0208 21:26:27.947064 139779755788032 __init__.py:44] file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/google/home/wangxf/Desktop/django-cloud-deploy/venv/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/wangxf/Desktop/django-cloud-deploy/venv/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/wangxf/Desktop/django-cloud-deploy/venv/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/wangxf/Desktop/django-cloud-deploy/venv/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/google/home/wangxf/Desktop/django-cloud-deploy/venv/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
/usr/local/google/home/wangxf/Desktop/django-cloud-deploy/venv/lib/python3.5/site-packages/googleapiclient/_helpers.py:130: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('2620:0:100e:913:e3db:a0d7:df2c:e5a6', 52000, 0, 0), raddr=('2607:f8b0:4005:801::200a', 443, 0, 0)>
  return wrapped(*args, **kwargs)
```

**Comment by wangxf123456** [comment]
Fixed by #263
