### ISSUE TITLE
NotImplementedError: cannot instantiate 'PosixPath' on your system

### ISSUE THREAD

**Issue by wangxf123456** [GoogleCloudPlatform/django-cloud-deploy#246]
## Issue running command
django-cloud-deploy new

## Environment information

Django Cloud Deploy: [0.1.6]

Platform: [Windows-10-10.0.17134-SP0]

Gcloud Version: [235.0.0]

Cloud SQL Proxy Version: [Cloud SQL Proxy: version 1.13; sha ac834ce67862b7c4ed8bdbe86e664572f820c245 built Tue Oct  9 23:39:16 UTC 2018]

Python Version: [3.7.1rc1 (v3.7.1rc1:2064bcf6ce, Sep 26 2018, 14:21:39) [MSC v.1914 32 bit (Intel)]]

Docker Version: [Not installed or not on PATH]

## Traceback
```.pytb
Traceback (most recent call last):
  File "c:\users\tiatia\django-cloud-deploy\django_cloud_deploy\django_cloud_deploy.py", line 36, in _new
    new.main(args)
  File "c:\users\tiatia\django-cloud-deploy\django_cloud_deploy\cli\new.py", line 213, in main
    backend=args.backend)
  File "c:\users\tiatia\django-cloud-deploy\django_cloud_deploy\workflow\__init__.py", line 220, in create_and_deploy_new_project
    project_id, cloud_storage_bucket_name, static_content_dir)
  File "c:\users\tiatia\django-cloud-deploy\django_cloud_deploy\workflow\_static_content_serve.py", line 46, in serve_static_content
    bucket_name, static_content_dir)
  File "c:\users\tiatia\django-cloud-deploy\django_cloud_deploy\cloudlib\static_content_serve.py", line 237, in upload_content
    directory_relative_path.replace('\\', '/'))
  File "c:\users\tiatia\appdata\local\programs\python\python37-32\Lib\pathlib.py", line 997, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'PosixPath' on your system

```

**Comment by brianquinlan** [comment]
Ahhh. I think that I should have used `PurePosixPath` instead of `PoxisPath`. I'll try to test with that and see that happens.
