### ISSUE TITLE
Unexpected response listing billing accounts (first test run)

### ISSUE THREAD

**Issue by gladiatr72** [GoogleCloudPlatform/django-cloud-deploy#278]
## Issue running command
django-cloud-deploy new

## Please describe what is wrong

I am not sure how to classify this issue.  It isn't a bug, per se, since the code looks to be running as intended.  This run-through used the prompts' defaults.

## Environment information

Django Cloud Deploy: [0.1.6]

Platform: [Linux-4.9.0-8-amd64-x86_64-with-debian-9.8]

Gcloud Version: [233.0.0]

Cloud SQL Proxy Version: [Cloud SQL Proxy: version 1.13; sha ac834ce67862b7c4ed8bdbe86e664572f820c245 built Tue Oct  9 23:39:16 UTC 2018]

Python Version: [3.6.5 (default, Apr 19 2018, 12:15:01)  [GCC 6.3.0 20170516]]

Docker Version: [Docker version 18.09.3, build 774a1f4]

## Traceback
```.pytb
Traceback (most recent call last):
  File "/home/gladiatr/git/django-cloud-deploy/v/django-cloud-deploy/django_cloud_deploy/django_cloud_deploy.py", line 36, in _new
    new.main(args)
  File "/home/gladiatr/git/django-cloud-deploy/v/django-cloud-deploy/django_cloud_deploy/cli/new.py", line 135, in main
    prompt_args)
  File "/home/gladiatr/git/django-cloud-deploy/v/django-cloud-deploy/django_cloud_deploy/cli/prompt.py", line 1129, in prompt
    console, step, new_args)
  File "/home/gladiatr/git/django-cloud-deploy/v/django-cloud-deploy/django_cloud_deploy/cli/prompt.py", line 733, in prompt
    only_open_accounts=True)
  File "/home/gladiatr/git/django-cloud-deploy/v/django-cloud-deploy/django_cloud_deploy/cloudlib/billing.py", line 108, in list_billing_accounts
    raise BillingError('Unexpected response listing billing accounts.')
django_cloud_deploy.cloudlib.billing.BillingError: Unexpected response listing billing accounts.

```

**Comment by gladiatr72** [comment]
received same results using an existing project-id

**Comment by enriquejosepadilla** [comment]
@gladiatr72 Thank you for opening this ticket, we are looking into it. We have a hypothesis of why that occurred, will update ticket when fix is in.

**Comment by wangxf123456** [comment]
This bug is fixed. We will do a release tomorrow to release the change to PyPI.
