### ISSUE TITLE
DeployNewAppError:Services to deploy.. Failed to deploy on last step.

### ISSUE THREAD

**Issue by enriquejosepadilla** [GoogleCloudPlatform/django-cloud-deploy#342]
## Issue running command
django-cloud-deploy cloudify

## Environment information

Django Cloud Deploy: [0.2.1]

Platform: [Linux-4.19.20-1rodete1-amd64-x86_64-with-Debian-rodete-rodete]

Gcloud Version: [231.0.0]

Cloud SQL Proxy Version: [Cloud SQL Proxy: version 1.13; sha ac834ce67862b7c4ed8bdbe86e664572f820c245 built Tue Oct  9 23:39:16 UTC 2018]

Python Version: [3.5.4rc1 (default, Jul 25 2017, 08:53:34)  [GCC 7.3.0]]

Docker Version: [Docker version 18.09.3, build 774a1f4]

## Traceback
```.pytb
Traceback (most recent call last):
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/django_cloud_deploy.py", line 46, in _cloudify
    cloudify.main(args)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/cli/cloudify.py", line 170, in main
    deploy_existing_django_project=True)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/workflow/__init__.py", line 290, in create_and_deploy_new_project
    project_id, django_directory_path, is_new=is_new)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/workflow/deploy_workflow.py", line 50, in deploy_gae_app
    region, is_new)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/workflow/_deploygae.py", line 101, in deploy_gae_app
    raise DeployNewAppError(gcloud_result.stderr)
django_cloud_deploy.workflow._deploygae.DeployNewAppError: Services to deploy:

descriptor:      [/usr/local/google/home/epad/Projects/shopping/app.yaml]
source:          [/usr/local/google/home/epad/Projects/shopping]
target project:  [django-cloudify-509674]
target service:  [default]
target version:  [20190402t200511]
target url:      [https://django-cloudify-509674.appspot.com]


Beginning deployment of service [default]...
#============================================================#
#= Uploading 65 files to Google Cloud Storage               =#
#============================================================#
File upload done.
Updating service [default]...
..........................................................................................................failed.
ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build 778c3bb2-86a2-41e8-b2c0-cecd349740b6 status: FAILURE.
Build error details: Build error details not available..
Check the build log for errors: https://console.cloud.google.com/gcr/builds/778c3bb2-86a2-41e8-b2c0-cecd349740b6?project=1026943860446


Checking logs on GCP shows: <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds. <ins>That’s all we know.</ins>

Should we retry this operation?

```

**Comment by wangxf123456** [comment]
I think we should retry this operation. I saw this error several times when doing integration tests for GAE.
