### ISSUE TITLE
Crash if the user enters a project id that already exists

### ISSUE THREAD

**Issue by brianquinlan** [GoogleCloudPlatform/django-cloud-deploy#37]
**Step 1 of 8: Create GCP Project**

Traceback (most recent call last):
  File "/usr/local/google/home/bquinlan/cloud/django-cloud-deploy/django-deploy/bin/django-cloud-deploy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/google/home/bquinlan/cloud/django-cloud-deploy/django-deploy/lib/python3.5/site-packages/django_cloud_deploy/django_cloud_deploy.py", line 57, in main
    args.func(args)
  File "/usr/local/google/home/bquinlan/cloud/django-cloud-deploy/django-deploy/lib/python3.5/site-packages/django_cloud_deploy/django_cloud_deploy.py", line 30, in _new
    new.main(args)
  File "/usr/local/google/home/bquinlan/cloud/django-cloud-deploy/django-deploy/lib/python3.5/site-packages/django_cloud_deploy/cli/new.py", line 175, in main
    actual_parameters['database_password'])
  File "/usr/local/google/home/bquinlan/cloud/django-cloud-deploy/django-deploy/lib/python3.5/site-packages/django_cloud_deploy/workflow/__init__.py", line 114, in create_and_deploy_new_project
    project_name, project_id)
  File "/usr/local/google/home/bquinlan/cloud/django-cloud-deploy/django-deploy/lib/python3.5/site-packages/django_cloud_deploy/workflow/_project.py", line 76, in create_project
    project_id, project_name)
  File "/usr/local/google/home/bquinlan/cloud/django-cloud-deploy/django-deploy/lib/python3.5/site-packages/django_cloud_deploy/cloudlib/project.py", line 110, in create_and_set_project
    self.create_project(project_id, project_name)
  File "/usr/local/google/home/bquinlan/cloud/django-cloud-deploy/django-deploy/lib/python3.5/site-packages/django_cloud_deploy/cloudlib/project.py", line 100, in create_project
    response = request.execute()
  File "/usr/local/google/home/bquinlan/cloud/django-cloud-deploy/django-deploy/lib/python3.5/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/google/home/bquinlan/cloud/django-cloud-deploy/django-deploy/lib/python3.5/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 409 when requesting https://cloudresourcemanager.googleapis.com/v1/projects?alt=json returned "Requested entity already exists">

Should display a nice error message instead.

**Comment by brianquinlan** [comment]
There are two aspects to this:
1. handling the exception, if it occurs
2. checking whether the project exists in advance

**Comment by wangxf123456** [comment]
Last week we added another flag "--use-existing-project" for external user testing. If this flag is set, then our tool will skip project name prompt and billing account prompt and use the values directly.

**Comment by brianquinlan** [comment]
Sure but we still need to do a better job if the user accidentally chooses an existing project.

**Comment by wangxf123456** [comment]
Yeah I completely agree. I just want to let you know that new change in case you missed that.
