### ISSUE TITLE
Update command fails if Django Python Packages are not in Django Cloud Deploy virtual environment

### ISSUE THREAD

**Issue by enriquejosepadilla** [GoogleCloudPlatform/django-cloud-deploy#40]
If my django app has python packages that are not in the django-cloud deploy tool, then when running update I get the following error log:

Traceback (most recent call last):
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/django/utils/module_loading.py", line 44, in autodiscover_modules
    if register_to:
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 526, in _setup
    AdminSiteClass = import_string(apps.get_app_config('admin').default_site)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/google/home/epad/django-project/cloud_admin/admin.py", line 4, in <module>
    from google.cloud import logging
ImportError: cannot import name 'logging'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/bin/django-cloud-deploy", line 11, in <module>
    load_entry_point('django-cloud-deploy', 'console_scripts', 'django-cloud-deploy')()
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/django_cloud_deploy.py", line 57, in main
    args.func(args)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/django_cloud_deploy.py", line 25, in _update
    update.main(args)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/cli/update.py", line 110, in main
    actual_parameters['database_password'])
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/workflow/__init__.py", line 201, in update_project
    database_password)
  File "/usr/local/google/home/epad/Projects/django-cloud-deploy/django_cloud_deploy/skeleton/source_generator.py", line 302, in setup_django_environment
    django.setup()
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/django/utils/module_loading.py", line 53, in autodiscover_modules
    if register_to:
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 526, in _setup
    AdminSiteClass = import_string(apps.get_app_config('admin').default_site)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-cloud-deploy-SCoBGI1n/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/google/home/epad/django-project/cloud_admin/admin.py", line 4, in <module>
    from google.cloud import logging
ImportError: cannot import name 'logging'

The cause of the issue is know, it is due to the update command attempting to run the django.setup() which runs the app. This might also cause a problem to new. 

Leaving this issue up for visibility.

**Comment by enriquejosepadilla** [comment]
This can be avoided by making sure the same virtual environment that uses our tool is the same as the django application.
