### ISSUE TITLE
Fail to download cloud_sql_proxy if the user does not have permission in the destination directory

### ISSUE THREAD

**Issue by wangxf123456** [GoogleCloudPlatform/django-cloud-deploy#83]
```bash
$ django-cloud-deploy new
Cloud Sql Proxy is required, download? [Y/n]:y
Downloading Cloud Sql Proxy
Traceback (most recent call last):
  File "/usr/local/google/home/wangxf/Desktop/code/django-cloud-deploy/django_cloud_deploy/tool_requirements.py", line 114, in check_and_handle
    cls.check()
  File "/usr/local/google/home/wangxf/Desktop/code/django-cloud-deploy/django_cloud_deploy/tool_requirements.py", line 184, in check
    raise MissingRequirementError(cls.NAME, msg)
django_cloud_deploy.tool_requirements.MissingRequirementError: ('Cloud Sql Proxy', 'Please download Cloud SQL Proxy from https://cloud.google.com/sql/docs/mysql/sql-proxy')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/wangxf/Desktop/code/django-cloud-deploy/venv/bin/django-cloud-deploy", line 11, in <module>
    load_entry_point('django-cloud-deploy', 'console_scripts', 'django-cloud-deploy')()
  File "/usr/local/google/home/wangxf/Desktop/code/django-cloud-deploy/django_cloud_deploy/django_cloud_deploy.py", line 57, in main
    args.func(args)
  File "/usr/local/google/home/wangxf/Desktop/code/django-cloud-deploy/django_cloud_deploy/django_cloud_deploy.py", line 30, in _new
    new.main(args)
  File "/usr/local/google/home/wangxf/Desktop/code/django-cloud-deploy/django_cloud_deploy/cli/new.py", line 115, in main
    tool_requirements.check_and_handle_requirements(console)
  File "/usr/local/google/home/wangxf/Desktop/code/django-cloud-deploy/django_cloud_deploy/tool_requirements.py", line 262, in check_and_handle_requirements
    req.check_and_handle(console)
  File "/usr/local/google/home/wangxf/Desktop/code/django-cloud-deploy/django_cloud_deploy/tool_requirements.py", line 117, in check_and_handle
    cls.handle(console)
  File "/usr/local/google/home/wangxf/Desktop/code/django-cloud-deploy/django_cloud_deploy/tool_requirements.py", line 197, in handle
    cls._download_cloud_sql_proxy(console)
  File "/usr/local/google/home/wangxf/Desktop/code/django-cloud-deploy/django_cloud_deploy/tool_requirements.py", line 234, in _download_cloud_sql_proxy
    with open(executable_name, 'wb') as file:
PermissionError: [Errno 13] Permission denied: '/usr/bin/cloud_sql_proxy'
```

**Comment by brianquinlan** [comment]
The download approach is obsolete now.
